### ISSUE TITLE
Workshop API - Tags

### ISSUE THREAD

**Issue by Emad88** [greenheartgames/greenworks#151]
Hello.
Is it possible to define tags when publishing and updating workshop items? 
According to the documentation, I can only define the title, description, and image.

Thanks

**Comment by Emad88** [comment]
Hi again,
I forked the project and implemented tags support, I compiled it for nw.js win-ia32  and tried it for a bit and it seems to work.
I will make a pull request when I complete all the workshop features to my game to make sure that there are no bugs.

A few questions and doubts:

- I added a "tags" parameter in _publishWorkshopFile_ and _updatePublishedWorkshopFile_ just before the callbacks. This will break compatibility with previous versions but I guess there is no way around it.

- How to delete all existing tags from an item? My current solution is that if you give updatePublishedWorkshopFile an empty tags array, the tags won't be updated (like the other string parameters), but if the array contains one empty string the existing tags will be deleted. Empty tags are otherwise skipped. Not a very clean solution but I couldn't think of another way. Let me know if you have a better idea.

- Is it necessary to execute _fileShare_ on the preview image and file after pushing them to Steam Cloud but before publishing a new Workshop item? It seems to work without it and when I do use it sometimes I get an error (maybe caused when I try to share a file already shared?). What is it for?

**Comment by hokein** [comment]
@Emad88 
Thanks for your effort on this! Contributions are always welcome. Feel free to send an pull request, and we can discuss there :).

> I added a "tags" parameter in publishWorkshopFile and updatePublishedWorkshopFile just before the callbacks. This will break compatibility with previous versions but I guess there is no way around it.

Yes, adding "tags" parameter would break the backward compatibility. But we could add an optional option at the beginning of the `publishWorkshopFile` and`updatePublishedWorkshopFile` APIs' parameter list, you can see my comments at https://github.com/greenheartgames/greenworks/pull/127.

I think we would make this option is an object `{tags: XXX}`, so that it can easily add extra options (e.g. AppID) in the future .

> How to delete all existing tags from an item? My current solution is that if you give updatePublishedWorkshopFile an empty tags array, the tags won't be updated (like the other string parameters), but if the array contains one empty string the existing tags will be deleted. Empty tags are otherwise skipped. Not a very clean solution but I couldn't think of another way. Let me know if you have a better idea.

The solution sounds good to me as long as it is well documented :)

> Is it necessary to execute fileShare on the preview image and file after pushing them to Steam Cloud but before publishing a new Workshop item?

I think so. By default, they are not enabled to be publicly visible in the Workshop. Can you get an error log and see what's happening?

BTW, the current Greenworks UGC APIs are using deprecated RemoteStorage based Workshop APIs. I think we need to support new UGC APIs based on ISteamUGC APIs.

**Comment by hokein** [comment]
Fixed in #194.
