### ISSUE TITLE
linux app crashes when run through steam client

### ISSUE THREAD

**Issue by riadd** [greenheartgames/greenworks#22]
I'm not sure that this is the right place, but when I deploy my linux app into steam, I can't run it from the steam client. Navigating to the app directory and starting the app directly from terminal works fine. Only when starting it through the "play" button from inside the steam client it prints out..

    ERROR: ld.so: object '/home/riad/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

Nothing else happens. As far as I can tell the error message is actually not the cause of the problem, as it seems to be expected for 64bit apps that are started from Steam.

There is a nw process running, but it does not open any windows. Clicking the play again results in a "app already running error message". I also looked for crash dumps in the /tmp/ folder but could only find logs that contain the error message above.

Is there some way to ramp up the verbosity of nw.js to give me a chance to understand what might be happening? Anybody having seen something similar or having an idea how I might debug this? Any help would be highly appreciated.

**Comment by hokein** [comment]
It looks like a Steam client issue since your game work finely through terminal. Howerver I can't tell the root cause. BTW, what's your linux system? You might google the log error message to find the reason.

**Comment by riadd** [comment]
I'm running a Ubuntu 14 distro through VMWare.

I saw the error message mentioned various times. It seems to be expected since steam will try to load both the 32bit and 64bit version of the overlay. This makes 64 bit systems always complaing about the 32 library and 32 bit systems always complain about the 64 bit library. It is still expected to work though.

Yea, I know it is probably more related to Steam than actual greenworks. Was just wondering if somebody over here had the same issue at some point or has some hints about how to debug it. :/

**Comment by riadd** [comment]
By explicitly removing the 64 bit version of the gameoverlayrenderer.so from the LD_PRELOAD path when running my game, I'm able to finally run it through Steam. The game still does not display the overlay in-game, but at least its not stuck in start-up anymore. I'll close this issue for now.

**Comment by janpetersen** [comment]
If it helps: We decided to stick to the 32bit release of our game. Since Steam itself is just a 32bit application, it seems to be more stable to distribute a 32bit application. Which in fact runs fine on my native 64bit Ubuntu 14.04 system. And btw., most games in the Steam shop are 32bit games, at least most of the simpler ones. You don't need to provide a 64bit release, if all your application does is to render some HTML5 animations.

The Steam overlay does not work, though. But it does not work in Game Dev Tycoon, either. Whether I use the 64bit or 32bit version of Game Dev Tycoon, doesn't matter: the Steam overlay won't work. Seems to be an issue with Steam itself, or with Steam trying to hook itself into the nw.js renderer.

And even Game Dev Tycoon works fine with both the 32bit and 64bit version (simply change the "start.sh" file to make the game launch the 32bit version on your 64bit machine). So why bother to provide a 64bit release, anyways?
