### ISSUE TITLE
How to debug 'false' result from initAPI() ?

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#34]
Hi,

I'm getting a false result from initAPI(), but no error or further information , so am now a bit stuck...

Under what conditions would initAPI() return false?
What can I do to debug this issue further?

Thank you

**Comment by hokein** [comment]
Please view the trouble shooting page: https://github.com/greenheartgames/greenworks/wiki/Troubleshooting

Have you launched the Steam Client?

**Comment by bgSosh** [comment]
Thanks for the response

I read through that page already, but I don't have any of these error messages, just a 'false' result, which is not covered on that page. (Perhaps these error messages are logged somewhere?) 

I confirm that the steam client is running on the machine, and I have the steam_appid.txt file in the application root.

**Comment by bgSosh** [comment]
I found this information on steam website :+1: 

  A return of false indicates one of three conditions:
  The Steam client isn't running. A running Steam client is required to provide implementations of the   various Steamworks interfaces.
  The Steam client couldn't determine the AppID of game. Make sure you have Steam_appid.txt in your   game directory.
  Your application is not running under the same user context as the Steam client, including admin privileges.

Turns out I needed to run nw.js as administrator, after which it returned true.

**Comment by hokein** [comment]
@bgSosh 
Glad to see you resolve it.

> Turns out I needed to run nw.js as administrator, after which it returned true.

Looks weird to me. From my previous experience, I don't need to run nw.js as administrator. 

>I found this information on steam website :

> A return of false indicates one of three conditions:
   The Steam client isn't running. A running Steam client is required to provide implementations of the   various Steamworks interfaces.
   The Steam client couldn't determine the AppID of game. Make sure you have Steam_appid.txt in your   game directory.
   Your application is not running under the same user context as the Steam client, including admin

Could you please add it to the https://github.com/greenheartgames/greenworks/wiki/Troubleshooting wiki page, so that it can help peolple when they meet the same issue. Thanks!

**Comment by bgSosh** [comment]
Sure, added!
