### ISSUE TITLE
Overlay not clickable without in-process-gpu switch - are there performance implications?

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#40]
It seems we need to use the --in-process-gpu switch, otherwise mouse interaction with the overlay breaks.

Does anyone know if there are performance implications in using the  --in-process-gpu switch?

**Comment by hokein** [comment]
> Does anyone know if there are performance implications in using the --in-process-gpu switch?

This problem is more like a nw.js/Chromium related problem. NW.js community is a more suitable place to ask, instead of aksing in Greenworks.

The `in-process-gpu` switch indicates Chromium runs the gpu thread in its browser process rather seperating a gpu process, which will reduce the cost of IPC message communitcation. Howerver, no one has done the profile compared with these two running mode.

**Comment by bgSosh** [comment]
Thanks for the info!
