### ISSUE TITLE
Still cannot build Greenworks for 0.13.x

### ISSUE THREAD

**Issue by AshleyScirra** [greenheartgames/greenworks#69]
I'm still at a loss how to get Greenworks working with my own build. This blocks us maintaining Greenworks support ourselves for Construct 2 users.

As a minimum first step all I'm trying to do is get Greenworks working with the "Hello Greenworks" sample on Windows x64 with NW.js 0.13.2. I've tried builds with both node-gyp (with hack applied) and nw-gyp. The build succeeds but the resulting .node file never works. Here's a win64 version of "Hello Greenworks" with the greenworks-win64.node file I've built myself (note sample is lightly modified to load everything from same folder):
https://dl.dropboxusercontent.com/u/15217362/greenworks-nwjs0-13-2.zip

This just starts up reporting "Error on initializing steam API.".

I built it against the latest Steamworks SDK (1.36), latest Greenworks source, and using node.js 5.9.0 (same as NW.js 0.13.2 uses).

When used in the Construct 2 engine, I also get either:
- an error message reporting the .node file cannot be found, and it reports the path to the file that does actually exist, or
- crashes on the require() line, and it's impossible to get any diagnostics because it brings down the devtools window too (and nothing is in debug.log)
I need to investigate these as well, but I don't think it makes sense to until I can get the "Hello Greenworks" sample working.

I am happy to pay for support here or make a donation. We have users awaiting commercial launch of Steam games built with Construct 2. We need either the Greenworks team to make regular releases to keep up with NW.js updates, or to figure out why our own builds aren't working. Any help appreciated.

**Comment by MadSpyxFR** [comment]
C2 221 and nw13.2foC2 works as intended with my build. 

And your file works
![scirragreenworkstest](https://cloud.githubusercontent.com/assets/16615206/14252736/eb4f0758-fa88-11e5-9a67-3966910633c9.jpg)

**Comment by TackerTacker** [comment]
It doesn't work for me and Steam was running
![greenworksc2](https://cloud.githubusercontent.com/assets/18266300/14253488/f482dc20-fa8b-11e5-85bb-3d4d54ab6e42.png)

**Comment by patrickklug** [comment]
I think rather than us facilitating donations which then go directly to the contractor anyway, maybe using something like https://www.bountysource.com/ would be more efficient. I believe this should work already and doesn't require any formal approval by us.

**Comment by MadSpyxFR** [comment]
I test the "hello greenworks" on win8.1 pro x64(new install on VM + important windows update) and the app runs
![scirragreenworkstest2](https://cloud.githubusercontent.com/assets/16615206/14332707/0929cf9c-fc4b-11e5-8b42-e0b1c6e4ace1.jpg)
but on win10, I have to launch the app via steam client with the correct steam app id else the hello greenworks doesn't initialize API

**Comment by hokein** [comment]
Greenworks v0.5.3 with SteamSDK 1.37 and nw.js 0.14.7 has been released. Please reopen the issue if you have any other problem.

**Comment by AshleyScirra** [comment]
NW.js 0.15 and 0.16 are already out. Is there not a way to make a single build that works with multiple versions??

**Comment by AshleyScirra** [comment]
The latest release is also missing the 32-bit versions again...

**Comment by hokein** [comment]
@AshleyScirra 

> NW.js 0.15 and 0.16 are already out. Is there not a way to make a single build that works with multiple versions??

No,  running a same native nodejs addon on multiple nw.js version is not always working because of ABI issues. It depends on V8, V8 is not always ABI compatible with every version. So every time nw.js upgrade, we have to rebuild greenworks.

> I am happy to pay for support here or make a donation. We have users awaiting commercial launch of Steam games built with Construct 2. We need either the Greenworks team to make regular releases to keep up with NW.js updates, or to figure out why our own builds aren't working. Any help appreciated.

If you could support this, that would be very appreciated.

What's Construct 2 requirement to Greenworks? Do you release Construct 2 every time nw.js upgrade? 

I totally agree that releasing Greenworks for every nw.js is a good idea, but currently we do the release manually (mainly by myself). And it's not worthy to setup builtbots (windows/macOS/linux) for a small plugin like Greenworks. The best way could be convincing nw.js guys to add our plugin to their builtbots, @patrickklug have contracted nw.js guys before, but haven't heard anything back.

> The latest release is also missing the 32-bit versions again...

Oh, sorry for missing that. I just read the  nw.js 0.14.7 release announcement published in mailing list. The announcement doesn't give 32-bit version download link directly. I have updated the release binaries now, including 32-bit versions.

**Comment by AshleyScirra** [comment]
Thanks for the updates.

For Construct 2 we update to the NW.js after every stable Chrome release, so the release versions of 0.14.0, 0.15.0, 0.16.0... etc. So that's about every six weeks. Providing a build of Greenworks for stable updates every six weeks would be perfect.
