### ISSUE TITLE
Thanks and Questions

### ISSUE THREAD

**Issue by jaykyburz** [greenheartgames/greenworks#79]
Hi Folks, I just wanted to say thanks very much for all your hard work on this project. I've been using Electron for about 2 hours now and I have my app mostly working and a build with Greenworks now as well. 

Quick question: Is it normal that the SDK would fail to initialize if Steam is not also running on the machine? Is that just how it works?

**Comment by jaykyburz** [comment]
Another question. What do you use to bundle the node application into a .app or .exe. 
I was looking at electron-packager but it seems to use the prebuild binaries which is not what we want here. https://github.com/electron-userland/electron-packager

**Comment by hokein** [comment]
> Is it normal that the SDK would fail to initialize if Steam is not also running on the machine? 

Yes, you have to run Steam client before running greenworks, otherwise the SDK API won't work.
You can see the detailed explanations from @dfabulich : https://github.com/greenheartgames/greenworks/pull/75

> What do you use to bundle our new electron build into a .app or .exe?

I'm not sure I understand your question correctly. Are you using a customized Electron instead of the official one? If so, you can hack the `electron-packager`, I think it won't be too hard.

**Comment by dfabulich** [comment]
I recommend `electron-builder` which wraps `electron-packager`.

**Comment by jaykyburz** [comment]
Thanks for the responses guys.
